import Evento from "./classes/Evento.js"
import {tEexpoArte, tEferia, tEfiesta, tEgastro, tEludico, tEmusica, tEtaller, tEteatro} from "./scripts/tiposDeEventos.js";
import {laMadriguera, barMutar, artesResistir, elPasaje} from "./scripts/centrosCulturales.js"


const baileInolvidable = new Evento(2, "baile inolvidable", artesResistir, new Date(2025, 10, 7, 23, 59), "Se viene la CUARTA EDICIÓN del fiestón que ya conocés. ¡Vuelve el BAILE INOLVIDABLE!🔥Presentamos la ultima edición del año con un F2F que te va a hacer bailar toda la noche 🫵🏻 Musicalizan🎧 @dj.monkey.arg 🆚 @marceloalvarezdj¿Listxs para ese duelo musical? 💣 Y como siempre, bancamos la fiesta y el bolsillo. La entrada es libre y gratuita, y ademas...✨¡HAY PROMO!✨ 🚀 2 TRAGOS x $10.000 🚀 (En fernet y vodka 🤌) ¿Nos vemos en la pista? 💿", "/img/baileInolvidableFlyer.png", tEfiesta);

const bsfArg = new Evento(3, "bsf tour argentina 2025", barMutar, new Date(2025, 10, 9, 21, 0), "✈️🌎ORIGINAL JUAN Y MARIANO DUQUE BSF TOUR ARGENTINA/AVELLANEDA🌎✈️ Original juan regresa a Argentina para redoblar su apuesta luego del rotundo éxito en su última pasada por nuestro suelo y nos toca recibirlo en Avellaneda por primera vez! Uno de los tipos más raperos del mundo en nuestra ciudad, no te quedes afuera.", "/img/bsfArg2025Flyer.webp", tEmusica);

const microclub = new Evento(1, "microclub", laMadriguera, new Date(2025, 10, 7, 23, 0), "", "/img/microclubFlyer.png", tEfiesta);
const cloverMuack = new Evento(4, "clover muack", elPasaje, new Date(2025, 10, 9, 12, 0), "¡¡¡Clover Muack!!! feria kawaii&k-pop Vuelve la edición mas aesthetic de Clover Producciones los esperamos el domingo 9 de Noviembre para vivir un día a puro K-Pop, moda y muchos colores pasteles 🤗 💖Stands 💖Shows en vivo 💖Invitadxs especiales 💖Flash tattoo 💖Y mucho mas!!! 📆Domingo 9 de Noviembre ⏰12:00HS 📍Centro Cultural El Pasaje Pasaje Estará 435 (Adrogué) 🎟️ENTRADA $3000 (Incluye: Bolsa C/Regalos exclusivos) MENORES DE 10 AÑOS Y COSPLAYERS GRATIS Organiza: @clover_producciones", "/img/cloverMuackFlyer.webp", tEferia);

const recheModo = new Evento(5, "reche modo, gitanos y nico spaziale + maggiolo", artesResistir, new Date(2025, 10, 15, 20, 0), "@rechemodo gitanosbluesbastardo @nico.spaziale @fermaggiolo La cita es en Arteresistir @artesresistir Anticipadas a $6000 por transferencia al alias: gitanosbluesbastardo (Enviar comprobante por privado) Fotografía por @diedefeo en @wacho55 @valiantnegrorecs Solo para valiantes: con el diablo en el interior.", "",  tEmusica);

const retroClover = new Evento(6, "retro clover", elPasaje, new Date(2025, 10, 21, 20, 0), "¡¡¡Retro Clover especial Dragon Ball 40 aniversario!!! ¡Prepárate para un noche épica! Celebramos el 40 aniversario de Dragon Ball con un evento nocturno que te hará sentir como un guerrero Z! 🎉 *Stand Up*: Disfruta de un espectáculo de comedia con los mejores comediantes de la escena local, inspirados en el universo de Dragon Ball. 🛍️ *Stands Comerciales*: Explora los stands y descubre los productos más increíbles de Dragon Ball, desde figuras de acción hasta ropa y accesorios. 🎤 *Karaoke*: Canta tus canciones favoritas de Dragon Ball con amigos y desconocidos en nuestro karaoke temático. 👗 *Cosplayers*: Admira a los mejores cosplayers de Dragon Ball, que te harán sentir como si estuvieras en el mundo de Goku y sus amigos. 📅 *Fecha y Hora*: Viernes 21 de Noviembre 20hs 📍 *Lugar*: Centro Cultural El Pasaje Pasaje Estrada 435 (Adrogué) ¡No te pierdas esta oportunidad de celebrar con nosotros! ENTRADA $10000 Organiza: @clover_producciones", "", tEferia);

const eventos = [baileInolvidable, microclub, recheModo, retroClover, bsfArg, cloverMuack];
export default eventos;